[package]
name = "simpla_vortaro"
description = "Access the Esperanto dictionary Simpla Vortaro"
version = "0.2.1"
authors = ["panicbit <panicbit.dev@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/panicbit/simpla_vortaro_rs"
documentation = "https://docs.rs/simpla_vortaro"

[dependencies]
reqwest = "0.8.4"
serde = { version = "1.0.27", features = ["serde_derive"] }
percent-encoding = "1.0.1"
clap = "2.30.0"
colored = "1.6.0"
itertools = "0.7.6"
textwrap = { version = "0.10.0", features = ["term_size"] }
